apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: pomonitoragentserv
  annotations:
    scenarios.ai.sap.com/description: "POMonitor Agent"
    scenarios.ai.sap.com/name: "pomonitoragent-scenario"
    executables.ai.sap.com/description: "executable to monitoer logs"
    executables.ai.sap.com/name: "pomonitoragent-exec"
  labels:
    ai.sap.com/version: 0.1.0
    scenarios.ai.sap.com/id: "pomonitoragent-scenario" 
spec:
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: rps
        autoscaling.knative.dev/target: 100
        autoscaling.knative.dev/targetBurstCapacity: 70
      labels: |
        ai.sap.com/resourcePlan: starter
    spec: |
      predictor:
        imagePullSecrets:
          - name: sudhadockerregistry
        minReplicas: 0
        maxReplicas: 2
        containers:
        - name: kserve-container
          image: docker.io/sudhasivarama/piagentdocimg:latest
          ports:
            - containerPort: 9001    # customizable port
              protocol: TCP
          env:
            - name: AICORE_BASE_URL # Name of the environment variable that will be available in the image
              valueFrom:
                secretKeyRef:
                  name: ai-core-credentials  # Name of the generic secret created in SAP AI Core for the Resource Group
                  key: AICORE_BASE_URL    # Name of the key from the JSON string that is saved as generic secret    
            - name: AICORE_AUTH_URL 
              valueFrom:
                secretKeyRef:
                  name: ai-core-credentials   
                  key: AICORE_AUTH_URL    
            - name: AICORE_CLIENT_ID 
              valueFrom:
                secretKeyRef:
                  name: ai-core-credentials   
                  key: AICORE_CLIENT_ID   
            - name: AICORE_CLIENT_SECRET 
              valueFrom:
                secretKeyRef:
                  name: ai-core-credentials   
                  key: AICORE_CLIENT_SECRET   
            - name: ENV_HARDCODED
              value: "here we can hardcode any values we just want to have in the template"
          command:
            - python
            - '-c'
          args:
            - |
              import os
              print("Hello from SAP AI Core ENV Demo")
              print(os.environ.get("AICORE_AUTH_URL", "not_set"))
              print(os.environ.get("ENV_HARDCODED", "not_set"))
              print(os.environ.get("AICORE_BASE_URL", "not_set"))
