apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: pomonitoragentserv
  annotations:
    scenarios.ai.sap.com/description: "POMonitor Agent"
    scenarios.ai.sap.com/name: "pomonitoragent-scenario"
    executables.ai.sap.com/description: "executable to monitoer logs"
    executables.ai.sap.com/name: "pomonitoragent-exec"
  labels:
    ai.sap.com/version: 0.1.0
    scenarios.ai.sap.com/id: "pomonitoragent-scenario" 
spec:
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: rps
        autoscaling.knative.dev/target: 100
        autoscaling.knative.dev/targetBurstCapacity: 70
      labels: |
        ai.sap.com/resourcePlan: starter
    spec: |
      predictor:
        imagePullSecrets:
          - name: sudhadockerregistry
        minReplicas: 0
        maxReplicas: 2
        containers:
        - name: kserve-container
          image: docker.io/sudhasivarama/piagentdocimg:latest
          ports:
            - containerPort: 9001    # customizable port
              protocol: TCP
          command: [python]
          args: [./btpaiagent.py]
          env:
            - name: AICORE_BASE_URL
              value: "https://api.ai.prod.eu-central-1.aws.ml.hana.ondemand.com/v2"
          envFrom:
            - secretRef:
                name: ai-core-credentials
