apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: pomonitoragentserv
  annotations:
    scenarios.ai.sap.com/description: "POMonitor Agent"
    scenarios.ai.sap.com/name: "pomonitoragent-scenario"
    executables.ai.sap.com/description: "executable to monitoer logs"
    executables.ai.sap.com/name: "pomonitoragent-exec"
    artifacts.ai.sap.com/textmodel.kind: "model"
    artifacts.ai.sap.com/textmodel.description: "POMonitor Artefact description"
    artifacts.ai.sap.com/textmodel.labels: | 
        {"ext.ai.sap.com/customkey1":"customvalue1", "ext.ai.sap.com/customkey2":"customvalue2"}
  labels:
    ai.sap.com/version: 0.1.0
    scenarios.ai.sap.com/id: "pomonitoragent-scenario" 
spec:
  inputs:
    parameters:
      - name: modelName
        default: value
        type: string
        description: description of the parameter
    artifacts:
      - name: textmodel
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: rps
        autoscaling.knative.dev/target: 100
        autoscaling.knative.dev/targetBurstCapacity: 70
      labels: |
        ai.sap.com/resourcePlan: starter
    spec: |
      predictor:
        imagePullSecrets:
          - name: sudhadockerregistry
        minReplicas: 0
        maxReplicas: 5
        containers:
        - name: kserve-container
          image: docker.io/sudhasivarama/piagentdocimg:latest
          ports:
          - containerPort: 9001
            protocol: TCP
          env:
          - name: STORAGE_URI
            value: "{{inputs.artifacts.textmodel}}"
